project:
  type: website
  output-dir: docs


website:
  title: "Claudio Robelo"
  site-url: "https://crobelo.github.io"
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Acerca de mí"
        href: about.qmd
      - text: "Cursos"
        menu:
          - text: "Todos los cursos"
            href: cursos/index.qmd
          # - text: "Métodos Cuantitativos"
          #   href: cursos/metodos-cuanti/index.qmd
  search: true
  page-navigation: true

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
lang: es

